### ISSUE TITLE
Improve search bar inputs' style

### ISSUE THREAD

**Issue by jasongitmail** [PyaeSoneAungRgn/github-zed-theme#1]
Great work on the theme!

Noticed one opportunity for improvement.

The find and replace inputs have an unusual background color, with a lighter gray rectangle inside them that seems unintentional:
<img width="1105" alt="" src="https://github.com/PyaeSoneAungRgn/github-zed-theme/assets/50032291/946600af-fe33-48a0-a44e-ee54bf064a08">

For comparison, here is One Dark Pro theme:
<img width="992" alt="" src="https://github.com/PyaeSoneAungRgn/github-zed-theme/assets/50032291/80355eb8-03b3-47b7-a2fa-e51ed4d7299a">

**Comment by PyaeSoneAungRgn** [comment]
Thanks you, i'll try to fix and release new version

**Comment by jasongitmail** [comment]
It turns out the slightly lighter color in the Github Dark theme's searhc input, is actually "editor.background"'s color showing through.
The solution is to make `"toolbar.background"` the same color as ` "editor.background"`.

I'll submit a PR.
