### ISSUE TITLE
Code completions are hard to read

### ISSUE THREAD

**Issue by dhbrojas** [PyaeSoneAungRgn/github-zed-theme#16]
The text color for code completions (Supermaven, Github Copilot) is set to black in the light theme and white in the dark theme. This makes it hard to read.

<img width="550" alt="Screenshot 2024-10-19 at 12 37 13" src="https://github.com/user-attachments/assets/711fdf02-2637-4c22-a648-b446d336abb2">

I recommend adding the following block in your Zed configuration.

```jsonc
{
  // ...
  "experimental.theme_overrides": {
    "predictive": "#808080"
  }
}
```

Here's what it looks like:

<img width="550" alt="Screenshot 2024-10-19 at 12 38 13" src="https://github.com/user-attachments/assets/45e7557c-0aaf-4541-9fc4-01bae60d4ace">
<img width="551" alt="Screenshot 2024-10-19 at 12 38 36" src="https://github.com/user-attachments/assets/c57a9d55-567d-4ad6-b1bf-1bfe800d835e">

@PyaeSoneAungRgn would you be willing to integrate this into the theme?

**Comment by PyaeSoneAungRgn** [comment]
Thanks you, i'm trying to fix issues at this weekend. I'll apply your changes.

**Comment by PyaeSoneAungRgn** [comment]
https://github.com/zed-industries/extensions/pull/1808/files fixed
